//
//  SignupInteractor.swift
//  CleanSwiftDemo
//
//  Created by KiwiTech on 28/01/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignupBusinessLogic
{
  func doSomething(request: Signup.Something.Request)
}

protocol SignupDataStore
{
  //var name: String { get set }
}

class SignupInteractor: SignupBusinessLogic, SignupDataStore
{
  var presenter: SignupPresentationLogic?
  var worker: SignupWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Signup.Something.Request)
  {
    worker = SignupWorker()
    worker?.doSomeWork()
    
    let response = Signup.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
