//
//  SignupPresenter.swift
//  CleanSwiftDemo
//
//  Created by KiwiTech on 28/01/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignupPresentationLogic
{
  func presentSomething(response: Signup.Something.Response)
}

class SignupPresenter: SignupPresentationLogic
{
  weak var viewController: SignupDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Signup.Something.Response)
  {
    let viewModel = Signup.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
