//
//  LoginPresenter.swift
//  CleanSwiftDemo
//
//  Created by KiwiTech on 28/01/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic
{
  func presentSomething(response: Login.Something.Response)
}

class LoginPresenter: LoginPresentationLogic
{
  weak var viewController: LoginDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Login.Something.Response)
  {
    guard let name = response.name else {
        return
    }
    let viewModel = Login.Something.ViewModel(name: name)
    viewController?.displaySomething(viewModel: viewModel)
    //check for error
    viewController?.showError(text: "aisud")
  }
}
