//
//  LoginWorker.swift
//  CleanSwiftDemo
//
//  Created by KiwiTech on 28/01/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class LoginWorker
{
    let apiStrore = LoginApiStore()
    func doSomeWork(comepletion: (Login.Something.Response) -> Void)
  {
  }
    func loginKaro(request: Login.Something.Request, completion: (Login.Something.Response) -> Void) throws {
        guard let email = request.email, let password = request.password else {
            throw ValidationErrors.blankField
        }
        apiStrore.loginAPIHitKaro(request: request, completion: completion)
    }
}
enum ValidationErrors: Error {
    case blankField
}
